language: php
script:
- echo "MY TEST"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out $TRAVIS_BUILD_DIR/deploy_key -d

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_key
  - ssh-add $TRAVIS_BUILD_DIR/deploy_key
  - mkdir -p ~/.ssh
  - echo -e "Host mywebsite.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

addons:
  ssh_known_hosts: 78.24.217.4
