language: php
script:
- echo "MY TEST"
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
